package hibernate;
// Generated 01-feb-2015 20:33:44 by Hibernate Tools 4.3.1



/**
 * Inmueble generated by hbm2java
 */
public class Inmueble  implements java.io.Serializable {


     private Integer id;
     private String usuario;
     private String localidad;
     private String calle;
     private String numero;
     private String tipo;
     private String precio;
     private String imagenes;

    public Inmueble() {
    }

    public Inmueble(String usuario, String localidad, String calle, String numero, String tipo, String precio, String imagenes) {
       this.usuario = usuario;
       this.localidad = localidad;
       this.calle = calle;
       this.numero = numero;
       this.tipo = tipo;
       this.precio = precio;
       this.imagenes = imagenes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public String getImagenes() {
        return this.imagenes;
    }
    
    public void setImagenes(String imagenes) {
        this.imagenes = imagenes;
    }




}


